### ISSUE TITLE
Unicode characters are not saved correctly.

### ISSUE THREAD

**Issue by 4Christopher** [lehrblogger/OkCupid-Message-Downloader#17]
Hi

Nice script :+1:. I have encountered a problem with unicode characters like ["…", "ö"]. They end up as ["â&euro;Ś", "รถ"]. I did not find the problem. The page is UTF-8 and the characters are not HTML entities or something. Any idea?

**Comment by joelpurra** [comment]
See strict dependency version locking to BeautifulSoup 3.2.1 in #24 .
