### ISSUE TITLE
Guess thread timestamp from message index

### ISSUE THREAD

**Issue by ckuethe** [lehrblogger/OkCupid-Message-Downloader#34]
In mutual matches there is no timestamp in the message after a user has deleted their account. Luckily, the message index has 

     span class="timestamp"

which can be used to extract a timestamp, eg. https://gist.github.com/ckuethe/1b524674c9cb2e637f10

Actually, it's not just deleted users. An unacknowledged mutual match has no timestamp either, but the timestamp span does have a better timestamp.

**Comment by lehrblogger** [comment]
Thanks for the fix!

(That gist doesn't work though, just FYI, but this still makes sense / matches the HTML I see.)
