### ISSUE TITLE
Password error (change in server login)

### ISSUE THREAD

**Issue by DavidMertz** [lehrblogger/OkCupid-Message-Downloader#43]
Tried the tool for the first time in a year.  I get this message on basic use:

```bash
% okcmd -u 'Lulu-Lotus-Eater' -p 'XXXXX' -f 'OKC.messages'
INFO: Queuing folder 1, page 0
ERROR: There was an error queuing the threads to download - are you sure your username and password are correct?
INFO: Done.
```

I've triple checked the password, and even reset it to something new just before trying again.  I also try with auto-login:

```bash
% okcmd -u 'Lulu-Lotus-Eater' --autologin 'https://www.okcupid.com/l/.5_FgAbRWoCOh.4IS9tZXNzYWdlcz9jZj1tZXNzYWdlX25vdGlmaWNhdGlvbg.3NV_ytT5itANVtTmVQAk6g.5CXZOXyjqscwsP3cXXXXXXXXXX=' --directory 'OKC.dir' -m
ERROR: Don't specify both autologin and password
ERROR: See 'okcmd --help' for all options.
INFO: Done.
```

Has anyone used the tool successfully recently?

Debug mode doesn't really provide much helpful:

```bash
% okcmd -u 'Lulu-Lotus-Eater' -p 'XXXXXX' -f 'OKC.messages' --debug
DEBUG: Debug mode turned on.
DEBUG: Using password.
DEBUG: Cookie jar: <cookielib.CookieJar[<Cookie __cfduid=d2ace6402586c287002bdc2a78c67ebfa1456800607 for .okcupid.com/>, <Cookie guest=4061573900565105878 for .okcupid.com/>]>
INFO: Queuing folder 1, page 0
ERROR: There was an error queuing the threads to download - are you sure your username and password are correct?
INFO: Done.
```

**Comment by joelpurra** [comment]
> Has anyone used the tool successfully recently?

Perhaps only developers, as I've detected a bug in the version released to PyPI. @lehrblogger will have to release a new version with the most recent commit, which should fix it.

If you clone this repository and run `./okcmd` from that directory, it should work just fine -- running it right now.

Thanks for letting us know -- and indeed, there isn't enough dogfooding ;)

**Comment by lehrblogger** [comment]
@DavidMertz Thanks for the issue! I had meant to push a new version to PyPi with that most recent commit but must have forgotten. `1.5` should be up there now, and works for me.

**Comment by DavidMertz** [comment]
I had tried the local `/okcmd`, but I was getting some weird issues about virtualenv and conda not playing nice together (which I don't think is directly related to the tool, but conflicted with the bash script).  I've pulled the new PyPi version and am running it apparently successfully (still queuing folders and pages; that may go on for a long while before it gets to downloading... I have years worth of conversations).

**Comment by joelpurra** [comment]
@lehrblogger: thanks for the release!

@DavidMertz: glad it works now -- thanks again!

**Comment by 5u2ie** [comment]
Does the scraper work for anyone currently?
Tried running:

`okcmd -u 'my_username' -p 'my_pw' -f 'message_output_file.txt' --debug`

and got:

`DEBUG: Debug mode turned on.
DEBUG: Using password.
DEBUG: Cookie jar: <CookieJar[<Cookie __cfduid=
*cookie strings here*
INFO: Queuing folder 1, page 0
ERROR: There was an error queuing the threads to download - are you sure your username and password are correct?
INFO: Done.`

What am I doing wrong?

**Comment by lehrblogger** [comment]
Thanks for the report! Unfortunately the scraper doesn't seem to be working for me either. I'll open a new issue and link back here, but I'm not sure when I or someone else will get a chance to try to fix it.
